version: '3.8'

services:
  mongo:
    image: mongo:5.0.6
    environment:
      - MONGO_URL=mongodb://mongo:27017/dev
    volumes:
      - mongo_data:/data/db:delegated
    ports:
      - 27017:27017
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=codely
      - POSTGRES_USER=codely
      - POSTGRES_DB=mooc-backend-dev
    ports:
      - '5432:5432'
    restart: always
  postgres-test:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=codely
      - POSTGRES_USER=codely
      - POSTGRES_DB=mooc-backend-test
    ports:
      - '5433:5432'
    restart: always

volumes:
  mongo_data:
