imports:
  - { resource: ./application.yaml }

services:
  Backoffice.EnvironmentArranger:
    class: ../../../../../tests/Contexts/Shared/infrastructure/elasticsearch/ElasticEnvironmentArranger
    arguments: ['backoffice', '@Backoffice.Shared.ElasticConnectionManager']
